#!/bin/bash
#
# session script using dmenu
#
# author: Martin Ohmann <martin@mohmann.de>
#

if pgrep -c dwm; then
  wm=dwm
elif pgrep -c i3; then
  wm=i3
else
  >&2 echo "unsupported wm"
  exit 1
fi

action="$(echo -e "1: suspend\n2: poweroff\n3: reboot\n4: restart $wm\n5: logout\n6: lock screen" | \
  dmenu_wrapper -b -p "Session:")"

case "$action" in
  *suspend)  	cmd="/usr/sbin/systemctl suspend -i";;
  *poweroff) 	cmd="/usr/sbin/systemctl poweroff -i";;
  *reboot) 		cmd="/usr/sbin/systemctl reboot -i";;
  *restart) 	
    if [ "$wm" = dwm ]; then
      cmd="killall dwm"
    else
      cmd="i3-msg restart"
    fi;;
  *logout)
    if [ "$wm" = dwm ]; then
      cmd="killall dwm-startup"
    else
      cmd="i3-msg exit"
    fi;;
  *screen) 		
    if [ "$wm" = dwm ]; then
      cmd="/usr/bin/xscreensaver-command -lock"
    else
      cmd="~/.config/i3/fuzzy-lock"
    fi;;
  *) exit 1;;
esac

eval exec "$cmd"
