#!/bin/sh

# default vpn profile
profile=dufresne

usage() {
  cat <<EOS
  usage: $(basename "$0") [<vpn-name>] [on|start|off|stop|status|show-active|all-off]
EOS
}

profile_connected() {
  status=$(systemctl show openvpn-client@$profile | grep -oP 'ActiveState=\K(\w+)')
  if [ "$status" = "active" ]; then
    return 0
  fi
  return 1
}

connect() {
  echo "connecting vpn profile '$1'."
  sudo systemctl start openvpn-client@"$1"
}

disconnect() {
  echo "disconnecting vpn profile '$1'."
  sudo systemctl stop openvpn-client@"$1"
}

active_profiles() {
  systemctl list-units | \
    grep -oP '(?<=openvpn-client@)([^\s\t]+)(?=\.service.*active)'
}

disconnect_active() {
  active_profiles | while read -r p; do
    disconnect "$p"
  done
}

[ $# -lt 1 ] && { usage; exit 1; }
[ $# -gt 1 ] && { profile="$1"; shift; }

if [ ! -f /etc/openvpn/client/"$profile".conf ]; then
  echo "unknown vpn profile '$profile'."
  exit 1
fi

case "$1" in
  on|start)
    if profile_connected; then
      echo "vpn profile '$profile' already connected."
      exit 0
    fi
    connect "$profile" ;;
  off|stop)
    if ! profile_connected; then
      echo "vpn profile '$profile' not connected."
      exit 0
    fi
    disconnect "$profile" ;;
  reconnect)
    $0 "$profile" stop
    $0 "$profile" start ;;
  status)
    systemctl status openvpn-client@"$profile" ;;
  show-active)
    active_profiles ;;
  all-off)
    disconnect_active ;;
  *)
    usage; exit 1;;
esac
