#!/bin/bash
#
# find files and edit them

output=$(which -a "$@" | sed 's/^/  /g')
echo "=> query: $@"
if [ $? -eq 0 ]; then
  for f in "$@"; do
    echo "=> found files: $f"
    files=$(which -a "$f")
    select g in $files all skip; do
      if [ "$g" == "all" ]; then
        vim -p $files
        break
      elif [ "$g" == "skip" ]; then
        break
      fi

      if [ "$g" != '' ]; then
        vim "$g"
      fi
      break
    done
  done
fi
